[package]
name = "airlang_bin"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "The Air Programming Language"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
airlang = { path = "../lib" }
env_logger = "0.9.0"
log = "0.4"